name: Terraform Azure CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  production:
    uses: ./.github/workflows/deploy-component.yml
    with:
      COMPONENT: "./iac/rg-azug-demo"
      ENVIRONMENT: production