name: Terraform Azure CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  development:
    uses: ./.github/workflows/deploy-component.yml
    with:
      WORKING_DIRECTORY: ./iac/rg-azug-demo
      ENVIRONMENT: development

  # production:
  #   needs: [development]
  #   uses: ./.github/workflows/deploy-component.yml
  #   with:
  #     COMPONENT: "./iac/rg-azug-demo"
  #     ENVIRONMENT: production